//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scooterki.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scooters_table
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Power { get; set; }
        public int Vmax { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        public byte IsAvilable { get; set; }
        public string PictureSrc { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
